#!/usr/bin/env bash

set -euo pipefail

CURR_BRANCH=$(git rev-parse --abbrev-ref HEAD)
MAIN_BRANCH=$(git for-each-ref \
    --format "%(refname:short)" \
    "refs/heads/main" \
    "refs/heads/master"
)

if [ "${CURR_BRANCH}" = "${MAIN_BRANCH}" ]; then
    1>&2 echo "cannot delete ${MAIN_BRANCH} branch"
    exit 1
fi

git checkout "${MAIN_BRANCH}" && git pull && git branch -d "${CURR_BRANCH}"
