#!/usr/bin/env bash

# stolen in part from https://twitter.com/thingskatedid/status/1316074032379248640

set -euo pipefail

if [ -t 0 ]; then
    has_stdin=f
else
    has_stdin=t
fi


# Look for command line flags.
while [ $# -gt 0 ]; do
    case "$1" in
    *)
        if [ -r "$1" ]; then
            has_stdin=f
            rsvg-convert "$1" | imgcat
        else
            error "isvg: $1: No such file or directory"
            exit 2
        fi
        ;;
    esac
    shift
done

# Read and print stdin
if [ $has_stdin = t ]; then
    rsvg-convert | imgcat
fi

exit 0
