#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.12"
# ///


import sys

total = 0
for line in sys.stdin:
    line = line.rstrip("\n")
    try:
        total += float(line)
    except ValueError:
        pass
print(total)
