#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.12"
# dependencies = ["ujson"]
# ///


import sys
from datetime import date, datetime

try:
    import ujson as json
except ImportError:
    import json
import yaml


def json_serial(obj):
    if isinstance(obj, (date, datetime)):
        return obj.isoformat()
    raise TypeError("Type %s not serializable" % type(obj))


with open(sys.argv[1], "r") if len(sys.argv) > 1 else sys.stdin as f:
    print(json.dumps(yaml.load(f, Loader=yaml.SafeLoader), default=json_serial))
