#!/usr/bin/env python3

import json
import sys
import yaml

from datetime import date, datetime


def json_serial(obj):
    if isinstance(obj, (date, datetime)):
        return obj.isoformat()
    raise TypeError("Type %s not serializable" % type(obj))


with open(sys.argv[1], 'r') if len(sys.argv) > 1 else sys.stdin as f:
    print(json.dumps(yaml.load(f, Loader=yaml.SafeLoader), default=json_serial))
